"""Nominal parallel-leg channel-section data in millimetres.

The drawing tool models the section stated in the brief: parallel flange faces,
a uniform web, and two inside fillets.  ``Z0`` is the published/reference
centroid distance from the outside face of the web; the actual insertion
centroid is calculated from the exact geometry generated by ``channel_geometry.py``.
"""

from __future__ import division

import math


def _parallel_leg_z0(h, b, tw, tf, r):
    """Return the centroid distance from the outside web face in mm.

    This matches the simplified, parallel-leg profile that the plug-in draws.
    It intentionally does not attempt to model the flange taper of other
    channel-section families.
    """
    web_area = tw * h
    flange_area = 2.0 * (b - tw) * tf
    sharp_area = web_area + flange_area
    sharp_mx = web_area * (tw / 2.0) + flange_area * ((b + tw) / 2.0)

    # Each re-entrant fillet adds one quarter of a circle to the sharp L form.
    fillet_area = 0.5 * math.pi * r * r
    fillet_x = tw + r - (4.0 * r / (3.0 * math.pi))
    return (sharp_mx + fillet_area * fillet_x) / (sharp_area + fillet_area)


def _section(h, b, tw, tf, r, z0=None):
    if z0 is None:
        z0 = _parallel_leg_z0(h, b, tw, tf, r)
    return {
        "H": float(h),
        "B": float(b),
        "tw": float(tw),
        "tf": float(tf),
        "r": float(r),
        "Z0": float(z0),
    }


# GB/T 706-style nominal sizes used by the supplied specification.  The
# geometry in this V1 plug-in is deliberately a parallel-leg representation.
CHANNEL_DATA = {
    "5": _section(50, 37, 4.5, 7.0, 7.0),
    "6.3": _section(63, 40, 4.8, 7.5, 7.5),
    "8": _section(80, 43, 5.0, 8.0, 8.0),
    "10": _section(100, 48, 5.3, 8.5, 8.5),
    "12": _section(120, 53, 5.5, 9.0, 9.0),
    "12.6": _section(126, 53, 5.5, 9.0, 9.0),
    "14a": _section(140, 58, 6.0, 9.5, 9.5),
    "14b": _section(140, 60, 8.0, 9.5, 9.5),
    "16a": _section(160, 63, 6.5, 10.0, 10.0),
    "16b": _section(160, 65, 8.5, 10.0, 10.0),
    "18a": _section(180, 68, 7.0, 10.5, 10.5),
    "18b": _section(180, 70, 9.0, 10.5, 10.5),
    "20a": _section(200, 73, 7.0, 11.0, 11.0, z0=21.9),
    "20b": _section(200, 75, 9.0, 11.0, 11.0),
    "22a": _section(220, 77, 7.0, 12.0, 12.0),
    "22b": _section(220, 79, 9.0, 12.0, 12.0),
    "25a": _section(250, 78, 7.0, 12.0, 12.0),
    "25b": _section(250, 80, 9.0, 12.0, 12.0),
    "25c": _section(250, 82, 11.0, 12.0, 12.0),
    "28a": _section(280, 82, 7.5, 12.5, 12.5),
    "28b": _section(280, 84, 9.5, 12.5, 12.5),
    "28c": _section(280, 86, 11.5, 12.5, 12.5),
    "30a": _section(300, 85, 7.5, 13.5, 13.5),
    "30b": _section(300, 87, 9.5, 13.5, 13.5),
    "30c": _section(300, 89, 11.5, 13.5, 13.5),
    "32a": _section(320, 88, 8.0, 14.0, 14.0),
    "32b": _section(320, 90, 10.0, 14.0, 14.0),
    "32c": _section(320, 92, 12.0, 14.0, 14.0),
    "36a": _section(360, 96, 9.0, 16.0, 16.0),
    "36b": _section(360, 98, 11.0, 16.0, 16.0),
    "36c": _section(360, 100, 13.0, 16.0, 16.0),
    "40a": _section(400, 100, 10.5, 18.0, 18.0),
    "40b": _section(400, 102, 12.5, 18.0, 18.0),
    "40c": _section(400, 104, 14.5, 18.0, 18.0),
}

DEFAULT_PROFILE = "20a"


def profile_names():
    """Return profile names in the same order as the standards table."""
    return tuple(CHANNEL_DATA.keys())


def get_section(profile_name):
    """Return an independent section-data dictionary for *profile_name*."""
    try:
        section = dict(CHANNEL_DATA[profile_name])
    except KeyError:
        raise ValueError("Unsupported channel profile: {0}".format(profile_name))
    validate_section(section)
    return section


def validate_section(section):
    """Raise ``ValueError`` when a section cannot produce a valid outline."""
    required = ("H", "B", "tw", "tf", "r", "Z0")
    missing = [name for name in required if name not in section]
    if missing:
        raise ValueError("Missing channel dimensions: {0}".format(", ".join(missing)))

    h, b = section["H"], section["B"]
    tw, tf, r = section["tw"], section["tf"], section["r"]
    if min(h, b, tw, tf, r) <= 0.0:
        raise ValueError("All channel dimensions must be positive.")
    if b <= tw + r:
        raise ValueError("B must be greater than tw + r.")
    if h <= 2.0 * (tf + r):
        raise ValueError("H is too small for two flange fillets.")
    if not 0.0 < section["Z0"] < b:
        raise ValueError("Z0 must lie between the web and flange tip.")
